[package]
name = "diskclearance"
version = "0.1.0"
description = "Safety-first storage analysis and cleanup"
authors = ["Md Habibur Rahman"]
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/aniklavida/diskclearance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "diskclearance_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
rusqlite = { version = "0.37", features = ["bundled"] }
ts-rs = "12.0.1"
serde_json = "1"
plist = "1.10.1"
sha2 = "0.10.8"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
