use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use ts_rs::TS;

use crate::boundary::destructive::*;
use crate::boundary::error::*;
use crate::boundary::events::*;
use crate::boundary::plan::*;
use crate::boundary::read::*;
use crate::foundation::FoundationStatus;

pub fn generate_typescript_bindings() -> String {
    let cfg = ts_rs::Config::default();
    let mut out = String::new();

    out.push_str("// This file was generated by export_types. Do not edit manually.\n\n");

    // Event channel names
    out.push_str("// Event channel names\n");
    out.push_str(&format!(
        "export const EVENT_SCAN_PROGRESS = \"{EVENT_SCAN_PROGRESS}\";\n"
    ));
    out.push_str(&format!(
        "export const EVENT_VERIFIED_COUNT = \"{EVENT_VERIFIED_COUNT}\";\n"
    ));
    out.push_str(&format!(
        "export const EVENT_COVERAGE_WARNING = \"{EVENT_COVERAGE_WARNING}\";\n"
    ));
    out.push_str(&format!(
        "export const EVENT_EXECUTION_OUTCOME = \"{EVENT_EXECUTION_OUTCOME}\";\n"
    ));
    out.push_str(&format!(
        "export const EVENT_TERMINAL_COMPLETION = \"{EVENT_TERMINAL_COMPLETION}\";\n\n"
    ));

    // Command names
    out.push_str("// Command names\n");
    out.push_str("export const COMMAND_FOUNDATION_STATUS = \"foundation_status\";\n");
    out.push_str("export const COMMAND_START_SCAN = \"start_scan\";\n");
    out.push_str("export const COMMAND_CANCEL_SCAN = \"cancel_scan\";\n");
    out.push_str("export const COMMAND_FETCH_FINDINGS_PAGE = \"fetch_findings_page\";\n");
    out.push_str("export const COMMAND_FETCH_FOLDER_AGGREGATE = \"fetch_folder_aggregate\";\n");
    out.push_str(
        "export const COMMAND_FETCH_APPLICATION_INVENTORY = \"fetch_application_inventory\";\n",
    );
    out.push_str("export const COMMAND_DETECT_EXACT_DUPLICATES = \"detect_exact_duplicates\";\n");
    out.push_str("export const COMMAND_BUILD_PLAN = \"build_plan\";\n");
    out.push_str("export const COMMAND_FETCH_PLAN = \"fetch_plan\";\n");
    out.push_str("export const COMMAND_REVALIDATE_PLAN = \"revalidate_plan\";\n");
    out.push_str("export const COMMAND_EXECUTE_PLAN = \"execute_plan\";\n");
    out.push_str("export const COMMAND_FETCH_HISTORY_OPERATIONS = \"fetch_history_operations\";\n");
    out.push_str("export const COMMAND_FETCH_OPERATION_DETAIL = \"fetch_operation_detail\";\n");
    out.push_str("export const COMMAND_RESTORE_ITEM = \"restore_item\";\n");
    out.push_str(
        "export const COMMAND_FETCH_LIFETIME_RECLAMATION_TOTALS = \"fetch_lifetime_reclamation_totals\";\n\n",
    );

    // Types
    macro_rules! emit_type {
        ($t:ty) => {
            out.push_str(&format!("export {}\n\n", <$t as TS>::decl(&cfg)));
        };
    }

    out.push_str("// Foundation\n");
    emit_type!(FoundationStatus);

    out.push_str("// Errors\n");
    emit_type!(CommandError);

    out.push_str("// Events\n");
    emit_type!(ScanPhase);
    emit_type!(ScanProgressPayload);
    emit_type!(VerifiedCountPayload);
    emit_type!(CoverageWarningPayload);
    emit_type!(ExecutionOutcomePayload);
    emit_type!(TerminalStatus);
    emit_type!(TerminalCompletionPayload);

    out.push_str("// Read capability\n");
    emit_type!(StartScanArgs);
    emit_type!(ScanSessionHeader);
    emit_type!(CancelScanArgs);
    emit_type!(CancelScanResult);
    emit_type!(FetchFindingsPageArgs);
    emit_type!(FindingItem);
    emit_type!(FindingsPage);
    emit_type!(FetchFolderAggregateArgs);
    emit_type!(FolderAggregateEntry);
    emit_type!(FolderAggregate);
    emit_type!(ApplicationEntry);
    emit_type!(ApplicationInventory);
    emit_type!(DetectDuplicatesArgs);
    emit_type!(DuplicateReport);

    out.push_str("// Safety class\n");
    emit_type!(crate::classify::class::SafetyClass);

    out.push_str("// Duplicates domain\n");
    emit_type!(crate::duplicates::StorageSharingKind);
    emit_type!(crate::duplicates::RetainedRule);
    emit_type!(crate::duplicates::DuplicateItem);
    emit_type!(crate::duplicates::DuplicateGroup);
    emit_type!(crate::duplicates::DuplicatePlanError);

    out.push_str("// Plan capability\n");
    emit_type!(BuildPlanArgs);
    emit_type!(ReviewPlanHeader);
    emit_type!(FetchPlanArgs);
    emit_type!(PlanItemSummary);
    emit_type!(ReviewPlan);
    emit_type!(RevalidatePlanArgs);
    emit_type!(RevalidationResult);

    out.push_str("// Destructive capability\n");
    emit_type!(ActionMode);
    emit_type!(ExecutePlanArgs);
    emit_type!(ItemOutcomeStatus);
    emit_type!(ItemOutcomeRecord);
    emit_type!(ExecutionSummary);

    out.push_str("// History and restore capability\n");
    emit_type!(crate::boundary::history::FetchHistoryOperationsArgs);
    emit_type!(crate::boundary::history::HistoryOperationSummary);
    emit_type!(crate::boundary::history::FetchOperationDetailArgs);
    emit_type!(crate::boundary::history::RestoreEligibility);
    emit_type!(crate::boundary::history::TrashHistoryItemDetail);
    emit_type!(crate::boundary::history::PermanentDeleteHistoryItemDetail);
    emit_type!(crate::boundary::history::HistoryItemDetail);
    emit_type!(crate::boundary::history::HistoryOperationDetail);
    emit_type!(crate::boundary::history::RestoreItemArgs);
    emit_type!(crate::boundary::history::RestoreItemSummary);
    emit_type!(crate::boundary::history::LifetimeReclamationTotals);

    out
}

pub fn format_with_prettier(content: &str) -> Option<String> {
    #[cfg(windows)]
    let program = "npx.cmd";
    #[cfg(not(windows))]
    let program = "npx";

    let mut child = Command::new(program)
        .args(["prettier", "--stdin-filepath", "bindings.ts"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    if let Some(mut stdin) = child.stdin.take() {
        let _ = stdin.write_all(content.as_bytes());
    }

    let output = child.wait_with_output().ok()?;
    if output.status.success() {
        String::from_utf8(output.stdout).ok()
    } else {
        None
    }
}

pub fn generate_formatted_typescript_bindings() -> String {
    let raw = generate_typescript_bindings();
    format_with_prettier(&raw).unwrap_or(raw)
}

pub fn default_bindings_path() -> PathBuf {
    // Relative to Cargo.toml (src-tauri) -> ../src/types/bindings.ts
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.join("../src/types/bindings.ts")
}

pub fn write_bindings(target: &Path) -> std::io::Result<()> {
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)?;
    }
    let content = generate_formatted_typescript_bindings();
    fs::write(target, content)
}

pub fn check_bindings(target: &Path) -> Result<bool, String> {
    if !target.exists() {
        return Err(format!("File does not exist: {}", target.display()));
    }
    let current = fs::read_to_string(target)
        .map_err(|e| format!("Failed to read {}: {e}", target.display()))?;
    let expected = generate_formatted_typescript_bindings();
    let current_normalized = current.replace("\r\n", "\n");
    let expected_normalized = expected.replace("\r\n", "\n");
    Ok(current_normalized == expected_normalized)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generated_bindings_are_in_sync() {
        let path = default_bindings_path();
        if !path.exists() {
            panic!(
                "Bindings file does not exist at {}. Run 'npm run types:generate'.",
                path.display()
            );
        }
        let matches = check_bindings(&path).expect("check_bindings");

        assert!(
            matches,
            "Committed TypeScript bindings in {} are stale! Regenerate them using 'npm run types:generate'.",
            path.display()
        );
    }
}
