// This file was generated by export_types. Do not edit manually.

// Event channel names
export const EVENT_SCAN_PROGRESS = "scan:progress";
export const EVENT_VERIFIED_COUNT = "scan:verified-count";
export const EVENT_COVERAGE_WARNING = "scan:warning";
export const EVENT_EXECUTION_OUTCOME = "execute:item-outcome";
export const EVENT_TERMINAL_COMPLETION = "scan:terminal";

// Command names
export const COMMAND_FOUNDATION_STATUS = "foundation_status";
export const COMMAND_START_SCAN = "start_scan";
export const COMMAND_CANCEL_SCAN = "cancel_scan";
export const COMMAND_FETCH_FINDINGS_PAGE = "fetch_findings_page";
export const COMMAND_FETCH_FOLDER_AGGREGATE = "fetch_folder_aggregate";
export const COMMAND_FETCH_APPLICATION_INVENTORY =
  "fetch_application_inventory";
export const COMMAND_BUILD_PLAN = "build_plan";
export const COMMAND_FETCH_PLAN = "fetch_plan";
export const COMMAND_REVALIDATE_PLAN = "revalidate_plan";
export const COMMAND_EXECUTE_PLAN = "execute_plan";

// Foundation
export type FoundationStatus = {
  product: string;
  status: string;
  platform: string;
  scanningImplemented: boolean;
  deletionImplemented: boolean;
};

// Errors
export type CommandError =
  | { kind: "permissionDenied"; path: string | null; reason: string }
  | { kind: "pathVanished"; path: string }
  | { kind: "changedAfterReview"; planId: string; details: string }
  | { kind: "unsupported"; feature: string; reason: string };

// Events
export type ScanPhase =
  "discovering" | "scanning" | "classifying" | "coalescing" | "complete";

export type ScanProgressPayload = {
  sessionId: string;
  phase: ScanPhase;
  currentScope: string;
  itemsVisited: bigint;
  bytesVisited: bigint;
};

export type VerifiedCountPayload = {
  sessionId: string;
  category: string;
  verifiedCount: bigint;
  verifiedBytes: bigint;
};

export type CoverageWarningPayload = {
  sessionId: string;
  path: string;
  warningCode: string;
  message: string;
};

export type ExecutionOutcomePayload = {
  planId: string;
  itemId: string;
  success: boolean;
  error: string | null;
  bytesFreed: bigint;
};

export type TerminalStatus = "completed" | "cancelled" | "failed";

export type TerminalCompletionPayload = {
  sessionId: string;
  status: TerminalStatus;
  totalItems: bigint;
  totalBytes: bigint;
  summaryMessage: string;
};

// Read capability
export type StartScanArgs = { roots: Array<string> };

export type ScanSessionHeader = {
  sessionId: string;
  startedAtMs: bigint;
  roots: Array<string>;
};

export type CancelScanArgs = { sessionId: string };

export type CancelScanResult = { sessionId: string; cancelled: boolean };

export type FetchFindingsPageArgs = {
  sessionId: string;
  cursor: string | null;
  limit: number;
};

export type FindingItem = {
  id: string;
  path: string;
  sizeBytes: bigint;
  category: string;
  actionKind: string;
};

export type FindingsPage = {
  sessionId: string;
  items: Array<FindingItem>;
  nextCursor: string | null;
  totalEstimated: bigint;
};

export type FetchFolderAggregateArgs = { sessionId: string; path: string };

export type FolderAggregateEntry = {
  name: string;
  path: string;
  sizeBytes: bigint;
  fileCount: bigint;
  isDir: boolean;
};

export type FolderAggregate = {
  path: string;
  totalSizeBytes: bigint;
  fileCount: bigint;
  children: Array<FolderAggregateEntry>;
};

export type ApplicationEntry = {
  bundleId: string;
  name: string;
  installPath: string;
  sizeBytes: bigint;
};

export type ApplicationInventory = { applications: Array<ApplicationEntry> };

// Plan capability
export type BuildPlanArgs = { sessionId: string; findingIds: Array<string> };

export type ReviewPlanHeader = {
  planId: string;
  sessionId: string;
  itemCount: bigint;
  totalBytes: bigint;
  createdAtMs: bigint;
};

export type FetchPlanArgs = { planId: string };

export type PlanItemSummary = {
  itemId: string;
  originalPath: string;
  sizeBytes: bigint;
  className: string;
  actionName: string;
  recoverable: boolean;
};

export type ReviewPlan = {
  planId: string;
  sessionId: string;
  items: Array<PlanItemSummary>;
  defaultActionMode: ActionMode;
  createdAtMs: bigint;
};

export type RevalidatePlanArgs = { planId: string };

export type RevalidationResult = {
  planId: string;
  isValid: boolean;
  staleItemIds: Array<string>;
};

// Destructive capability
export type ActionMode = "trash" | "permanentDelete";

export type ExecutePlanArgs = { planId: string; actionMode: ActionMode };

export type ExecutionSummary = {
  planId: string;
  actionMode: ActionMode;
  succeededItems: bigint;
  failedItems: bigint;
  bytesFreed: bigint;
};
