// This file was generated by export_types. Do not edit manually.

// Event channel names
export const EVENT_SCAN_PROGRESS = "scan:progress";
export const EVENT_VERIFIED_COUNT = "scan:verified-count";
export const EVENT_COVERAGE_WARNING = "scan:warning";
export const EVENT_EXECUTION_OUTCOME = "execute:item-outcome";
export const EVENT_TERMINAL_COMPLETION = "scan:terminal";

// Command names
export const COMMAND_FOUNDATION_STATUS = "foundation_status";
export const COMMAND_START_SCAN = "start_scan";
export const COMMAND_CANCEL_SCAN = "cancel_scan";
export const COMMAND_FETCH_FINDINGS_PAGE = "fetch_findings_page";
export const COMMAND_FETCH_FOLDER_AGGREGATE = "fetch_folder_aggregate";
export const COMMAND_FETCH_APPLICATION_INVENTORY =
  "fetch_application_inventory";
export const COMMAND_DETECT_EXACT_DUPLICATES = "detect_exact_duplicates";
export const COMMAND_BUILD_PLAN = "build_plan";
export const COMMAND_FETCH_PLAN = "fetch_plan";
export const COMMAND_REVALIDATE_PLAN = "revalidate_plan";
export const COMMAND_EXECUTE_PLAN = "execute_plan";
export const COMMAND_FETCH_HISTORY_OPERATIONS = "fetch_history_operations";
export const COMMAND_FETCH_OPERATION_DETAIL = "fetch_operation_detail";
export const COMMAND_RESTORE_ITEM = "restore_item";
export const COMMAND_FETCH_LIFETIME_RECLAMATION_TOTALS =
  "fetch_lifetime_reclamation_totals";

// Foundation
export type FoundationStatus = {
  product: string;
  status: string;
  platform: string;
  scanningImplemented: boolean;
  deletionImplemented: boolean;
};

// Errors
export type CommandError =
  | { kind: "permissionDenied"; path: string | null; reason: string }
  | { kind: "pathVanished"; path: string }
  | { kind: "changedAfterReview"; planId: string; details: string }
  | { kind: "unsupported"; feature: string; reason: string };

// Events
export type ScanPhase =
  "discovering" | "scanning" | "classifying" | "coalescing" | "complete";

export type ScanProgressPayload = {
  sessionId: string;
  phase: ScanPhase;
  currentScope: string;
  itemsVisited: bigint;
  bytesVisited: bigint;
};

export type VerifiedCountPayload = {
  sessionId: string;
  category: string;
  verifiedCount: bigint;
  verifiedBytes: bigint;
};

export type CoverageWarningPayload = {
  sessionId: string;
  path: string;
  warningCode: string;
  message: string;
};

export type ExecutionOutcomePayload = {
  planId: string;
  itemId: string;
  success: boolean;
  error: string | null;
  bytesFreed: bigint;
};

export type TerminalStatus = "completed" | "cancelled" | "failed";

export type TerminalCompletionPayload = {
  sessionId: string;
  status: TerminalStatus;
  totalItems: bigint;
  totalBytes: bigint;
  summaryMessage: string;
};

// Read capability
export type StartScanArgs = { roots: Array<string> };

export type ScanSessionHeader = {
  sessionId: string;
  startedAtMs: bigint;
  roots: Array<string>;
};

export type CancelScanArgs = { sessionId: string };

export type CancelScanResult = { sessionId: string; cancelled: boolean };

export type FetchFindingsPageArgs = {
  sessionId: string;
  cursor: string | null;
  limit: number;
};

export type FindingItem = {
  id: string;
  path: string;
  sizeBytes: bigint;
  category: string;
  actionKind: string;
};

export type FindingsPage = {
  sessionId: string;
  items: Array<FindingItem>;
  nextCursor: string | null;
  totalEstimated: bigint;
};

export type FetchFolderAggregateArgs = { sessionId: string; path: string };

export type FolderAggregateEntry = {
  name: string;
  path: string;
  sizeBytes: bigint;
  fileCount: bigint;
  isDir: boolean;
};

export type FolderAggregate = {
  path: string;
  totalSizeBytes: bigint;
  fileCount: bigint;
  children: Array<FolderAggregateEntry>;
};

export type ApplicationEntry = {
  bundleId: string;
  name: string;
  installPath: string;
  sizeBytes: bigint;
};

export type ApplicationInventory = { applications: Array<ApplicationEntry> };

export type DetectDuplicatesArgs = {
  roots: Array<string>;
  retainedRule: RetainedRule | null;
};

export type DuplicateReport = {
  groups: Array<DuplicateGroup>;
  totalReclaimableBytes: bigint;
  totalDuplicateBytes: bigint;
};

// Safety class
export type SafetyClass = "rebuildable" | "review" | "protected";

// Duplicates domain
export type StorageSharingKind = "independent" | "hardlink" | "apfsClone";

export type RetainedRule =
  "oldestByModified" | "newestByModified" | "shortestPath";

export type DuplicateItem = {
  id: string;
  path: string;
  canonicalPath: string;
  sizeBytes: bigint;
  modifiedMs: bigint | null;
  inode: bigint;
  deviceId: bigint;
  isRetained: boolean;
  /**
   * Selection status. Invariant: always false by default.
   */
  isSelected: boolean;
  sharingKind: StorageSharingKind;
};

export type DuplicateGroup = {
  groupId: string;
  sizeBytes: bigint;
  contentHash: string;
  /**
   * Duplicates always classify as Review to require explicit user decision.
   */
  safetyClass: SafetyClass;
  /**
   * The structurally designated retained copy.
   */
  retained: DuplicateItem;
  /**
   * Independent candidate copies that can be chosen for deletion.
   */
  candidates: Array<DuplicateItem>;
  /**
   * Copies that share storage (hardlinks/APFS clones) contributing zero reclaimable bytes.
   */
  sharedStorageItems: Array<DuplicateItem>;
  /**
   * Net reclaimable bytes (only counts independent candidates, not shared storage or retained).
   */
  reclaimableBytes: bigint;
  /**
   * Total apparent bytes across all copies in the group.
   */
  totalGroupBytes: bigint;
};

export type DuplicatePlanError =
  | {
      kind: "retainedItemProtected";
      details: { group_id: string; path: string };
    }
  | { kind: "entireGroupSelected"; details: { group_id: string } }
  | {
      kind: "storageSharingItemNotDeletable";
      details: { group_id: string; path: string };
    }
  | { kind: "itemNotFound"; details: { group_id: string; item_id: string } }
  | { kind: "noItemsSelected"; details: { group_id: string } };

// Plan capability
export type BuildPlanArgs = { sessionId: string; findingIds: Array<string> };

export type ReviewPlanHeader = {
  planId: string;
  sessionId: string;
  itemCount: bigint;
  totalBytes: bigint;
  createdAtMs: bigint;
};

export type FetchPlanArgs = { planId: string };

export type PlanItemSummary = {
  itemId: string;
  originalPath: string;
  sizeBytes: bigint;
  className: string;
  actionName: string;
  recoverable: boolean;
};

export type ReviewPlan = {
  planId: string;
  sessionId: string;
  items: Array<PlanItemSummary>;
  defaultActionMode: ActionMode;
  createdAtMs: bigint;
};

export type RevalidatePlanArgs = { planId: string };

export type RevalidationResult = {
  planId: string;
  isValid: boolean;
  staleItemIds: Array<string>;
};

// Destructive capability
export type ActionMode = "trash" | "permanentDelete";

export type ExecutePlanArgs = { planId: string; actionMode: ActionMode };

export type ItemOutcomeStatus =
  | "succeeded"
  | "failed"
  | "skippedProtected"
  | "blockedChanged"
  | "vanished"
  | "permissionDenied"
  | "unattempted";

export type ItemOutcomeRecord = {
  itemId: string;
  originalPath: string;
  status: ItemOutcomeStatus;
  bytesReclaimed: bigint;
  bytesPendingTrash: bigint;
  errorMessage: string | null;
  trashedPath: string | null;
};

export type ExecutionSummary = {
  planId: string;
  actionMode: ActionMode;
  succeededItems: bigint;
  failedItems: bigint;
  bytesFreed: bigint;
  bytesPendingTrash: bigint;
  skippedProtected: bigint;
  blockedChanged: bigint;
  vanishedItems: bigint;
  permissionDeniedItems: bigint;
  itemOutcomes: Array<ItemOutcomeRecord>;
  operationId: string | null;
};

// History and restore capability
export type FetchHistoryOperationsArgs = {
  outcomeFilter: string | null;
  dateFromMs: bigint | null;
  dateToMs: bigint | null;
};

export type HistoryOperationSummary = {
  id: string;
  planId: string;
  actionMode: ActionMode;
  createdAtMs: bigint;
  completedAtMs: bigint;
  succeededItems: bigint;
  failedItems: bigint;
  skippedItems: bigint;
  blockedItems: bigint;
  vanishedItems: bigint;
  permissionDeniedItems: bigint;
  bytesPendingTrash: bigint;
  bytesPermanentlyReclaimed: bigint;
  totalItems: bigint;
};

export type FetchOperationDetailArgs = {
  operationId: string;
  outcomeFilter: string | null;
};

export type RestoreEligibility =
  | {
      status: "eligible";
      trashed_path: string;
      original_destination: string;
      destination_occupied: boolean;
      suggested_alternate_destination: string | null;
    }
  | { status: "ineligible"; reason: string }
  | { status: "restored"; restored_to_path: string; restored_at_ms: bigint };

export type TrashHistoryItemDetail = {
  operationItemId: string;
  itemId: string;
  originalPath: string;
  trashedPath: string | null;
  sizeBytes: bigint;
  status: ItemOutcomeStatus;
  bytesPendingTrash: bigint;
  errorMessage: string | null;
  createdAtMs: bigint;
  restoreEligibility: RestoreEligibility;
};

export type PermanentDeleteHistoryItemDetail = {
  operationItemId: string;
  itemId: string;
  originalPath: string;
  sizeBytes: bigint;
  status: ItemOutcomeStatus;
  bytesPermanentlyReclaimed: bigint;
  errorMessage: string | null;
  createdAtMs: bigint;
};

export type HistoryItemDetail =
  | ({ actionType: "trash" } & TrashHistoryItemDetail)
  | ({ actionType: "permanentDelete" } & PermanentDeleteHistoryItemDetail);

export type HistoryOperationDetail = {
  operation: HistoryOperationSummary;
  items: Array<HistoryItemDetail>;
};

export type RestoreItemArgs = {
  operationItemId: string;
  alternateDestination: string | null;
};

export type RestoreItemSummary = {
  restoreId: string;
  operationItemId: string;
  restoredToPath: string;
  sizeBytes: bigint;
  restoredAtMs: bigint;
};

export type LifetimeReclamationTotals = {
  pendingInTrashBytes: bigint;
  permanentlyReclaimedBytes: bigint;
};
