use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::classify::class::SafetyClass;
use crate::classify::evidence::{Confidence, Evidence, Recoverability};
use crate::classify::matcher::{MatchContext, RuleMatcher};
use crate::classify::protected::{PROTECTED_ROOTS, evaluate_protected_roots};

/// Declarative descriptor of a classification rule.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct RuleDescriptor {
    pub id: String,
    pub version: u32,
    pub owning_tool: String,
    pub resulting_class: SafetyClass,
    pub confidence: Confidence,
    pub user_sentence: String,
    pub what_regenerates: Option<String>,
    pub regeneration_cost: Option<String>,
    pub recoverability: Recoverability,
}

/// A rule entry with its runtime matcher.
pub struct CatalogueRule {
    pub descriptor: RuleDescriptor,
    pub matcher: RuleMatcher,
}

/// Complete classified finding produced by the rule catalogue.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ClassifiedFinding {
    pub path: String,
    pub canonical_path: String,
    pub size_bytes: u64,
    pub safety_class: SafetyClass,
    pub evidence: Evidence,
}

/// The declarative rule catalogue.
pub struct RuleCatalogue {
    rules: Vec<CatalogueRule>,
}

impl Default for RuleCatalogue {
    fn default() -> Self {
        Self::new()
    }
}

impl RuleCatalogue {
    pub fn new() -> Self {
        let rules = vec![

        // 1. Rebuildable rules with verified owning tools and regeneration commands
            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.rebuildable.cargo_target".to_string(),
                version: 1,
                owning_tool: "Cargo".to_string(),
                resulting_class: SafetyClass::Rebuildable,
                confidence: Confidence::Definite,
                user_sentence: "Rust build artifacts generated by Cargo compilation.".to_string(),
                what_regenerates: Some("cargo build".to_string()),
                regeneration_cost: Some("minutes to hours, depending on dependencies".to_string()),
                recoverability: Recoverability::RebuildableByTool {
                    command: "cargo build".to_string(),
                },
            },
            matcher: RuleMatcher::HomeRelativePrefix(".cargo/registry/cache".into()),
            },

            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.rebuildable.xcode_derived_data".to_string(),
                version: 1,
                owning_tool: "Xcode".to_string(),
                resulting_class: SafetyClass::Rebuildable,
                confidence: Confidence::Definite,
                user_sentence: "Intermediate build products, module caches, and symbol indexes generated by Xcode.".to_string(),
                what_regenerates: Some("xcodebuild".to_string()),
                regeneration_cost: Some("minutes to hours, plus dependency downloads".to_string()),
                recoverability: Recoverability::RebuildableByTool {
                    command: "xcodebuild".to_string(),
                },
            },
            matcher: RuleMatcher::HomeRelativePrefix("Library/Developer/Xcode/DerivedData".into()),
            },

            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.rebuildable.homebrew_cache".to_string(),
                version: 1,
                owning_tool: "Homebrew".to_string(),
                resulting_class: SafetyClass::Rebuildable,
                confidence: Confidence::Definite,
                user_sentence: "Downloaded bottle archives and source tarballs cached by Homebrew."
                    .to_string(),
                what_regenerates: Some("brew fetch".to_string()),
                regeneration_cost: Some("minutes, plus network downloads".to_string()),
                recoverability: Recoverability::RebuildableByTool {
                    command: "brew fetch".to_string(),
                },
            },
            matcher: RuleMatcher::CachesRelativePrefix("Homebrew".into()),
            },

            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.rebuildable.npm_cache".to_string(),
                version: 1,
                owning_tool: "npm".to_string(),
                resulting_class: SafetyClass::Rebuildable,
                confidence: Confidence::Definite,
                user_sentence: "Downloaded package tarballs and metadata cached by npm."
                    .to_string(),
                what_regenerates: Some("npm install".to_string()),
                regeneration_cost: Some("minutes, plus package downloads".to_string()),
                recoverability: Recoverability::RebuildableByTool {
                    command: "npm install".to_string(),
                },
            },
            matcher: RuleMatcher::HomeRelativePrefix(".npm/_cacache".into()),
            },

            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.rebuildable.gradle_cache".to_string(),
                version: 1,
                owning_tool: "Gradle".to_string(),
                resulting_class: SafetyClass::Rebuildable,
                confidence: Confidence::Definite,
                user_sentence: "Compiled dependency artifacts and wrapper jars cached by Gradle."
                    .to_string(),
                what_regenerates: Some("gradle build".to_string()),
                regeneration_cost: Some("minutes to hours, plus dependency downloads".to_string()),
                recoverability: Recoverability::RebuildableByTool {
                    command: "gradle build".to_string(),
                },
            },
            matcher: RuleMatcher::HomeRelativePrefix(".gradle/caches".into()),
            },

            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.rebuildable.go_build_cache".to_string(),
                version: 1,
                owning_tool: "Go".to_string(),
                resulting_class: SafetyClass::Rebuildable,
                confidence: Confidence::Definite,
                user_sentence: "Intermediate compilation outputs cached by the Go toolchain."
                    .to_string(),
                what_regenerates: Some("go build".to_string()),
                regeneration_cost: Some("seconds to minutes, plus module downloads".to_string()),
                recoverability: Recoverability::RebuildableByTool {
                    command: "go build".to_string(),
                },
            },
            matcher: RuleMatcher::CachesRelativePrefix("go-build".into()),
            },

        // 2. Review rules
            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.review.durable_models".to_string(),
                version: 1,
                owning_tool: "AI Model Runtime".to_string(),
                resulting_class: SafetyClass::Review,
                confidence: Confidence::Definite,
                user_sentence: "Durable machine learning model weights requiring explicit user review before cleanup.".to_string(),
                what_regenerates: None,
                regeneration_cost: None,
                recoverability: Recoverability::Irrecoverable,
            },
            matcher: RuleMatcher::DurableModelStorage,
            },

            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.review.downloads".to_string(),
                version: 1,
                owning_tool: "macOS User Space".to_string(),
                resulting_class: SafetyClass::Review,
                confidence: Confidence::Definite,
                user_sentence:
                    "User downloaded files requiring personal inspection before removal."
                        .to_string(),
                what_regenerates: None,
                regeneration_cost: None,
                recoverability: Recoverability::TrashRecoverable,
            },
            matcher: RuleMatcher::HomeRelativePrefix("Downloads".into()),
            },

            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.review.git_working_tree".to_string(),
                version: 1,
                owning_tool: "Git".to_string(),
                resulting_class: SafetyClass::Review,
                confidence: Confidence::Definite,
                user_sentence: "Files inside a Git working tree requiring manual verification against local modifications.".to_string(),
                what_regenerates: None,
                regeneration_cost: None,
                recoverability: Recoverability::SourceControlled { remote: None },
            },
            matcher: RuleMatcher::GitWorkingTreeUserFile,
            },

            CatalogueRule {
            descriptor: RuleDescriptor {
                id: "rule.review.mount_boundary".to_string(),
                version: 1,
                owning_tool: "macOS VFS".to_string(),
                resulting_class: SafetyClass::Review,
                confidence: Confidence::Definite,
                user_sentence:
                    "Filesystem crossing a device or mount boundary requiring explicit review."
                        .to_string(),
                what_regenerates: None,
                regeneration_cost: None,
                recoverability: Recoverability::Irrecoverable,
            },
            matcher: RuleMatcher::MountBoundaryCrossed,
            },

            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.rebuildable.project_build_output".to_string(),
                    version: 1,
                    owning_tool: "Project build tool".to_string(),
                    resulting_class: SafetyClass::Rebuildable,
                    confidence: Confidence::Definite,
                    user_sentence: "Generated output from a project build in a conventional output directory.".to_string(),
                    what_regenerates: Some("project build command".to_string()),
                    regeneration_cost: Some("seconds to hours, depending on the project".to_string()),
                    recoverability: Recoverability::RebuildableByTool { command: "project build command".to_string() },
                },
                matcher: RuleMatcher::BuildOutput,
             },

             CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.review.xcode_archives".to_string(),
                    version: 1,
                    owning_tool: "Xcode".to_string(),
                    resulting_class: SafetyClass::Review,
                    confidence: Confidence::Definite,
                    user_sentence: "Xcode archives may contain distributable apps, symbols, and diagnostics.".to_string(),
                    what_regenerates: None,
                    regeneration_cost: None,
                    recoverability: Recoverability::Irrecoverable,
                },
                matcher: RuleMatcher::HomeRelativePrefix("Library/Developer/Xcode/Archives".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.review.xcode_device_support".to_string(),
                    version: 1,
                    owning_tool: "Xcode".to_string(),
                    resulting_class: SafetyClass::Review,
                    confidence: Confidence::Definite,
                    user_sentence: "Xcode device support files are tied to debugging a physical device and may need download.".to_string(),
                    what_regenerates: None,
                    regeneration_cost: None,
                    recoverability: Recoverability::Irrecoverable,
                },
                matcher: RuleMatcher::HomeRelativePrefix("Library/Developer/Xcode/iOS DeviceSupport".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.rebuildable.ios_simulator_runtimes".to_string(),
                    version: 1,
                    owning_tool: "Xcode".to_string(),
                    resulting_class: SafetyClass::Rebuildable,
                    confidence: Confidence::Definite,
                    user_sentence: "Downloaded iOS Simulator runtimes managed by Xcode.".to_string(),
                    what_regenerates: Some("xcodebuild -downloadPlatform iOS".to_string()),
                    regeneration_cost: Some("multi-gigabyte download; often tens of minutes".to_string()),
                    recoverability: Recoverability::RebuildableByTool { command: "xcodebuild -downloadPlatform iOS".to_string() },
                },
                matcher: RuleMatcher::HomeRelativePrefix("Library/Developer/CoreSimulator/Profiles/Runtimes".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.review.ios_simulator_devices".to_string(),
                    version: 1,
                    owning_tool: "Xcode".to_string(),
                    resulting_class: SafetyClass::Review,
                    confidence: Confidence::Definite,
                    user_sentence: "Simulator devices can contain app data and state; inspect before removal.".to_string(),
                    what_regenerates: Some("xcrun simctl create".to_string()),
                    regeneration_cost: Some("minutes, but device state and app data are not recreated".to_string()),
                    recoverability: Recoverability::Irrecoverable,
                },
                matcher: RuleMatcher::HomeRelativePrefix("Library/Developer/CoreSimulator/Devices".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.review.container_images".to_string(),
                    version: 1,
                    owning_tool: "Docker Desktop".to_string(),
                    resulting_class: SafetyClass::Review,
                    confidence: Confidence::Likely,
                    user_sentence: "Docker Desktop VM storage can contain images and runtime data; inspect individual entries.".to_string(),
                    what_regenerates: None,
                    regeneration_cost: None,
                    recoverability: Recoverability::Irrecoverable,
                },
                matcher: RuleMatcher::HomeRelativePrefix("Library/Containers/com.docker.docker/Data/vms/0/data".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.rebuildable.docker_buildx_cache".to_string(),
                    version: 1,
                    owning_tool: "Docker Buildx".to_string(),
                    resulting_class: SafetyClass::Rebuildable,
                    confidence: Confidence::Definite,
                    user_sentence: "Docker Buildx builder state and build cache data.".to_string(),
                    what_regenerates: Some("docker buildx build".to_string()),
                    regeneration_cost: Some("minutes to hours, plus base-image downloads".to_string()),
                    recoverability: Recoverability::RebuildableByTool { command: "docker buildx build".to_string() },
                },
                matcher: RuleMatcher::HomeRelativePrefix(".docker/buildx".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.rebuildable.podman_image_cache".to_string(),
                    version: 1,
                    owning_tool: "Podman".to_string(),
                    resulting_class: SafetyClass::Rebuildable,
                    confidence: Confidence::Definite,
                    user_sentence: "Podman image and layer cache outside its protected volume store.".to_string(),
                    what_regenerates: Some("podman pull or podman build".to_string()),
                    regeneration_cost: Some("minutes to hours, plus image downloads".to_string()),
                    recoverability: Recoverability::RebuildableByTool { command: "podman pull or podman build".to_string() },
                },
                matcher: RuleMatcher::HomeRelativePrefix(".local/share/containers/storage/overlay".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.rebuildable.pip_cache".to_string(),
                    version: 1,
                    owning_tool: "pip".to_string(),
                    resulting_class: SafetyClass::Rebuildable,
                    confidence: Confidence::Definite,
                    user_sentence: "Downloaded Python wheels and source archives cached by pip.".to_string(),
                    what_regenerates: Some("pip install".to_string()),
                    regeneration_cost: Some("minutes, plus package downloads".to_string()),
                    recoverability: Recoverability::RebuildableByTool { command: "pip install".to_string() },
                },
                matcher: RuleMatcher::CachesRelativePrefix("pip".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.rebuildable.uv_cache".to_string(),
                    version: 1,
                    owning_tool: "uv".to_string(),
                    resulting_class: SafetyClass::Rebuildable,
                    confidence: Confidence::Definite,
                    user_sentence: "Downloaded Python packages and build artifacts cached by uv.".to_string(),
                    what_regenerates: Some("uv sync".to_string()),
                    regeneration_cost: Some("minutes, plus package downloads".to_string()),
                    recoverability: Recoverability::RebuildableByTool { command: "uv sync".to_string() },
                },
                matcher: RuleMatcher::CachesRelativePrefix("uv".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.rebuildable.yarn_cache".to_string(),
                    version: 1,
                    owning_tool: "Yarn".to_string(),
                    resulting_class: SafetyClass::Rebuildable,
                    confidence: Confidence::Definite,
                    user_sentence: "Downloaded package archives cached by Yarn.".to_string(),
                    what_regenerates: Some("yarn install".to_string()),
                    regeneration_cost: Some("minutes, plus package downloads".to_string()),
                    recoverability: Recoverability::RebuildableByTool { command: "yarn install".to_string() },
                },
                matcher: RuleMatcher::CachesRelativePrefix("Yarn".into()),
            },
            CatalogueRule {
                descriptor: RuleDescriptor {
                    id: "rule.rebuildable.pnpm_store".to_string(),
                    version: 1,
                    owning_tool: "pnpm".to_string(),
                    resulting_class: SafetyClass::Rebuildable,
                    confidence: Confidence::Definite,
                    user_sentence: "The pnpm content-addressable package store.".to_string(),
                    what_regenerates: Some("pnpm install".to_string()),
                    regeneration_cost: Some("minutes, plus package downloads".to_string()),
                    recoverability: Recoverability::RebuildableByTool { command: "pnpm install".to_string() },
                },
                matcher: RuleMatcher::HomeRelativePrefix("Library/pnpm/store".into()),
            },
        ];

        Self { rules }
    }

    /// Returns a list of descriptors for all rules in the catalogue (including protected roots).
    pub fn all_descriptors(&self) -> Vec<RuleDescriptor> {
        let mut list = Vec::new();

        // Include protected roots as versioned rules in the snapshot
        for root in PROTECTED_ROOTS {
            list.push(RuleDescriptor {
                id: root.id.to_string(),
                version: 1,
                owning_tool: "macOS Security Architecture".to_string(),
                resulting_class: SafetyClass::Protected,
                confidence: Confidence::Definite,
                user_sentence: root.description.to_string(),
                what_regenerates: None,
                regeneration_cost: None,
                recoverability: Recoverability::Irrecoverable,
            });
        }

        // Include active domain rules
        for r in &self.rules {
            list.push(r.descriptor.clone());
        }

        // Sort by rule ID for stable snapshot comparison
        list.sort_by(|a, b| a.id.cmp(&b.id));
        list
    }

    /// Produces a deterministic JSON snapshot of all rules in the catalogue.
    pub fn snapshot_json(&self) -> String {
        serde_json::to_string_pretty(&self.all_descriptors())
            .expect("rule catalogue serialization must not fail")
    }

    /// Classifies an entry according to the strict safety hierarchy.
    ///
    /// The classification hierarchy enforces:
    /// 1. Protected roots ALWAYS override any rule.
    /// 2. Symlinks pointing to protected or external areas are Protected or Review.
    /// 3. Cross-mount boundary crossings are never Rebuildable (downgraded to Review).
    /// 4. Files inside Git working trees are Review (not Rebuildable) unless explicitly clean-build verified.
    /// 5. Durable model stores are never Rebuildable (Review).
    /// 6. Active rebuildable rules only apply if verified owner and safe boundaries.
    /// 7. Everything else defaults to Review.
    pub fn classify(&self, ctx: &MatchContext<'_>) -> ClassifiedFinding {
        if ctx.inside_git_repo
            && let Some(rule) = self.rules.iter().find(|rule| {
                rule.descriptor.id == "rule.rebuildable.project_build_output"
                    && rule.matcher.evaluate(ctx).matched
            })
        {
            let result = rule.matcher.evaluate(ctx);
            let evidence = Evidence {
                rule_id: rule.descriptor.id.clone(),
                rule_version: rule.descriptor.version,
                owning_tool: rule.descriptor.owning_tool.clone(),
                matched_reason: result.explanation,
                regenerator: rule.descriptor.what_regenerates.clone(),
                regeneration_cost: rule.descriptor.regeneration_cost.clone(),
                last_activity_ms: ctx.modified_ms,
                recoverability: rule.descriptor.recoverability.clone(),
                confidence: rule.descriptor.confidence,
            };
            evidence
                .validate()
                .expect("build output evidence must be valid");
            return ClassifiedFinding {
                path: ctx.original_path.to_string_lossy().to_string(),
                canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
                size_bytes: ctx.apparent_size,
                safety_class: SafetyClass::Rebuildable,
                evidence,
            };
        }

        // Priority 1: Protected root evaluation
        if let Some(reason) = evaluate_protected_roots(ctx) {
            let evidence = Evidence {
                rule_id: reason.root_id,
                rule_version: 1,
                owning_tool: "macOS Protection Architecture".to_string(),
                matched_reason: reason.description.clone(),
                regenerator: None,
                last_activity_ms: ctx.modified_ms,
                regeneration_cost: None,
                recoverability: Recoverability::Irrecoverable,
                confidence: Confidence::Definite,
            };
            evidence
                .validate()
                .expect("protected evidence must be valid");

            return ClassifiedFinding {
                path: ctx.original_path.to_string_lossy().to_string(),
                canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
                size_bytes: ctx.apparent_size,
                safety_class: SafetyClass::Protected,
                evidence,
            };
        }

        // Priority 2: Symlink pointing to protected or external target
        if ctx.is_symlink
            && let Some(target) = &ctx.symlink_target_canonical
        {
            // If symlink target is a protected root or outside cache scope
            let target_ctx = MatchContext {
                original_path: target,
                canonical_path: target,
                normalized_path: target,
                entry_type: ctx.entry_type,
                identity: ctx.identity,
                apparent_size: ctx.apparent_size,
                allocated_size: ctx.allocated_size,
                modified_ms: ctx.modified_ms,
                is_symlink: false,
                symlink_target_canonical: None,
                home_dir: ctx.home_dir,
                app_support_dir: ctx.app_support_dir,
                caches_dir: ctx.caches_dir,
                crosses_mount_boundary: ctx.crosses_mount_boundary,
                inside_git_repo: ctx.inside_git_repo,
                is_git_internal: ctx.is_git_internal,
            };
            if let Some(reason) = evaluate_protected_roots(&target_ctx) {
                let evidence = Evidence {
                    rule_id: "rule.protection.symlink_target_protected".to_string(),
                    rule_version: 1,
                    owning_tool: "Symlink Safety Guard".to_string(),
                    matched_reason: format!(
                        "Symlink points to protected target: {} ({})",
                        target.display(),
                        reason.description
                    ),
                    regenerator: None,
                    last_activity_ms: ctx.modified_ms,
                    regeneration_cost: None,
                    recoverability: Recoverability::Irrecoverable,
                    confidence: Confidence::Definite,
                };
                evidence.validate().expect("symlink evidence must be valid");

                return ClassifiedFinding {
                    path: ctx.original_path.to_string_lossy().to_string(),
                    canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
                    size_bytes: ctx.apparent_size,
                    safety_class: SafetyClass::Protected,
                    evidence,
                };
            }

            // If symlink points into a user git repo or source tree
            if target_ctx.inside_git_repo {
                let evidence = Evidence {
                    rule_id: "rule.review.symlink_into_source_tree".to_string(),
                    rule_version: 1,
                    owning_tool: "Symlink Safety Guard".to_string(),
                    matched_reason: format!(
                        "Symlink points into source-controlled working tree: {}",
                        target.display()
                    ),
                    regenerator: None,
                    last_activity_ms: ctx.modified_ms,
                    regeneration_cost: None,
                    recoverability: Recoverability::SourceControlled { remote: None },
                    confidence: Confidence::Definite,
                };
                evidence.validate().expect("symlink evidence must be valid");

                return ClassifiedFinding {
                    path: ctx.original_path.to_string_lossy().to_string(),
                    canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
                    size_bytes: ctx.apparent_size,
                    safety_class: SafetyClass::Review,
                    evidence,
                };
            }
        }

        // Priority 3: Mount boundary crossed
        if ctx.crosses_mount_boundary {
            let evidence = Evidence {
                rule_id: "rule.review.mount_boundary".to_string(),
                rule_version: 1,
                owning_tool: "macOS VFS".to_string(),
                matched_reason: "Item crossed a filesystem mount boundary during traversal"
                    .to_string(),
                regenerator: None,
                last_activity_ms: ctx.modified_ms,
                regeneration_cost: None,
                recoverability: Recoverability::Irrecoverable,
                confidence: Confidence::Definite,
            };
            evidence
                .validate()
                .expect("mount boundary evidence must be valid");

            return ClassifiedFinding {
                path: ctx.original_path.to_string_lossy().to_string(),
                canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
                size_bytes: ctx.apparent_size,
                safety_class: SafetyClass::Review,
                evidence,
            };
        }

        // Priority 4: Durable model stores
        let is_durable_model = RuleMatcher::DurableModelStorage.evaluate(ctx);
        if is_durable_model.matched {
            let model_owner = ctx
                .home_dir
                .filter(|home| ctx.canonical_path.starts_with(home.join(".ollama/models")))
                .map(|_| "Ollama")
                .or_else(|| {
                    ctx.home_dir
                        .filter(|home| {
                            ctx.canonical_path
                                .starts_with(home.join(".cache/huggingface/hub"))
                        })
                        .map(|_| "Hugging Face")
                })
                .unwrap_or("Local AI model store");
            let evidence = Evidence {
                rule_id: "rule.review.durable_models".to_string(),
                rule_version: 1,
                owning_tool: model_owner.to_string(),
                matched_reason: format!(
                    "{} ({} bytes, {} GB). Re-downloading is the only way to get it back.",
                    is_durable_model.explanation,
                    ctx.apparent_size,
                    ctx.apparent_size / (1024 * 1024 * 1024)
                ),
                regenerator: None,
                last_activity_ms: ctx.modified_ms,
                regeneration_cost: None,
                recoverability: Recoverability::Irrecoverable,
                confidence: Confidence::Definite,
            };
            evidence.validate().expect("model evidence must be valid");

            return ClassifiedFinding {
                path: ctx.original_path.to_string_lossy().to_string(),
                canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
                size_bytes: ctx.apparent_size,
                safety_class: SafetyClass::Review,
                evidence,
            };
        }

        // Priority 5: Git working tree restriction
        // Any cache sitting inside a .git working tree is Review unless explicitly verified
        if ctx.inside_git_repo {
            let evidence = Evidence {
                rule_id: "rule.review.git_working_tree".to_string(),
                rule_version: 1,
                owning_tool: "Git".to_string(),
                matched_reason: "Item is located inside a Git working tree; classified as Review"
                    .to_string(),
                regenerator: None,
                last_activity_ms: ctx.modified_ms,
                regeneration_cost: None,
                recoverability: Recoverability::SourceControlled { remote: None },
                confidence: Confidence::Definite,
            };
            evidence
                .validate()
                .expect("git working tree evidence must be valid");

            return ClassifiedFinding {
                path: ctx.original_path.to_string_lossy().to_string(),
                canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
                size_bytes: ctx.apparent_size,
                safety_class: SafetyClass::Review,
                evidence,
            };
        }

        // Priority 6: Active declarative rules (Rebuildable & Review)
        for rule in &self.rules {
            let res = rule.matcher.evaluate(ctx);
            if res.matched {
                let evidence = Evidence {
                    rule_id: rule.descriptor.id.clone(),
                    rule_version: rule.descriptor.version,
                    owning_tool: rule.descriptor.owning_tool.clone(),
                    matched_reason: res.explanation,
                    regenerator: rule.descriptor.what_regenerates.clone(),
                    regeneration_cost: rule.descriptor.regeneration_cost.clone(),
                    last_activity_ms: ctx.modified_ms,
                    recoverability: rule.descriptor.recoverability.clone(),
                    confidence: rule.descriptor.confidence,
                };
                evidence.validate().expect("evidence must be valid");

                return ClassifiedFinding {
                    path: ctx.original_path.to_string_lossy().to_string(),
                    canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
                    size_bytes: ctx.apparent_size,
                    safety_class: rule.descriptor.resulting_class,
                    evidence,
                };
            }
        }

        // Priority 7: Default fallback to Review
        let fallback_evidence = Evidence {
            rule_id: "rule.review.unclassified_artifact".to_string(),
            rule_version: 1,
            owning_tool: "Heuristic Classifier".to_string(),
            matched_reason: "Unclassified filesystem item; requires manual user review".to_string(),
            regenerator: None,
            regeneration_cost: None,
            last_activity_ms: ctx.modified_ms,
            recoverability: Recoverability::TrashRecoverable,
            confidence: Confidence::Likely,
        };
        fallback_evidence
            .validate()
            .expect("fallback evidence must be valid");

        ClassifiedFinding {
            path: ctx.original_path.to_string_lossy().to_string(),
            canonical_path: ctx.canonical_path.to_string_lossy().to_string(),
            size_bytes: ctx.apparent_size,
            safety_class: SafetyClass::Review,
            evidence: fallback_evidence,
        }
    }
}
