use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Confidence level of a rule classification match.
///
/// Surfaced to the UI so heuristic matches can be clearly communicated as
/// "likely" rather than an absolute fact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub enum Confidence {
    /// Exact match on canonical path, bundle identity, or verified tool structure.
    Definite,
    /// Heuristic match requiring user awareness and cautious handling.
    Likely,
}

impl Confidence {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Definite => "definite",
            Self::Likely => "likely",
        }
    }
}

/// Structured explanation of an item's recoverability if removed.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, TS)]
#[serde(tag = "kind", content = "details", rename_all = "camelCase")]
pub enum Recoverability {
    /// Cannot be regenerated automatically (e.g. user documents, credentials, manual configuration).
    Irrecoverable,
    /// Can be regenerated by invoking a specific developer or system tool.
    RebuildableByTool { command: String },
    /// Can be restored via Trash Put Back if moved to Trash rather than permanently deleted.
    TrashRecoverable,
    /// Preserved in an upstream source-control repository (e.g. git commit).
    SourceControlled { remote: Option<String> },
}

impl Recoverability {
    pub fn is_rebuildable(&self) -> bool {
        matches!(self, Self::RebuildableByTool { .. })
    }
}

/// Structured evidence accompanying every classified finding.
///
/// Evidence is machine-readable structured data, never an opaque formatted string.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Evidence {
    /// Stable identifier of the rule that produced this classification.
    pub rule_id: String,
    /// Version of the rule when the finding was produced.
    pub rule_version: u32,
    /// Name of the tool or application owning this filesystem artifact.
    pub owning_tool: String,
    /// Plain explanation of why the path matched this rule.
    pub matched_reason: String,
    /// Command or action that regenerates the artifact, if rebuildable.
    pub regenerator: Option<String>,
    /// Last detected activity timestamp (epoch milliseconds), if available.
    pub last_activity_ms: Option<u64>,
    /// Rough time and bandwidth cost of regenerating this item.
    pub regeneration_cost: Option<String>,
    /// Recoverability assessment for this item.
    pub recoverability: Recoverability,
    /// Match confidence level (definite vs likely).
    pub confidence: Confidence,
}

/// Errors emitted when an evidence record fails validation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "kind", content = "details", rename_all = "camelCase")]
pub enum EvidenceValidationError {
    EmptyRuleId,
    ZeroRuleVersion,
    EmptyOwningTool,
    EmptyMatchedReason,
}

impl std::fmt::Display for EvidenceValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyRuleId => write!(f, "evidence rule_id must not be empty"),
            Self::ZeroRuleVersion => write!(f, "evidence rule_version must be greater than zero"),
            Self::EmptyOwningTool => write!(f, "evidence owning_tool must not be empty"),
            Self::EmptyMatchedReason => write!(f, "evidence matched_reason must not be empty"),
        }
    }
}

impl std::error::Error for EvidenceValidationError {}

impl Evidence {
    /// Validates that an evidence record is non-empty and well-formed.
    pub fn validate(&self) -> Result<(), EvidenceValidationError> {
        if self.rule_id.trim().is_empty() {
            return Err(EvidenceValidationError::EmptyRuleId);
        }
        if self.rule_version == 0 {
            return Err(EvidenceValidationError::ZeroRuleVersion);
        }
        if self.owning_tool.trim().is_empty() {
            return Err(EvidenceValidationError::EmptyOwningTool);
        }
        if self.matched_reason.trim().is_empty() {
            return Err(EvidenceValidationError::EmptyMatchedReason);
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_valid_evidence_passes_validation() {
        let evidence = Evidence {
            rule_id: "rule.cargo.target".to_string(),
            rule_version: 1,
            owning_tool: "Cargo".to_string(),
            matched_reason: "Matches Cargo build target directory".to_string(),
            regenerator: Some("cargo build".to_string()),
            last_activity_ms: Some(1700000000),
            regeneration_cost: Some("minutes to hours".to_string()),
            recoverability: Recoverability::RebuildableByTool {
                command: "cargo build".to_string(),
            },
            confidence: Confidence::Definite,
        };
        assert!(evidence.validate().is_ok());
    }

    #[test]
    fn test_evidence_rejects_empty_fields() {
        let mut evidence = Evidence {
            rule_id: "".to_string(),
            rule_version: 1,
            owning_tool: "Cargo".to_string(),
            matched_reason: "Reason".to_string(),
            regenerator: None,
            last_activity_ms: None,
            regeneration_cost: None,
            recoverability: Recoverability::TrashRecoverable,
            confidence: Confidence::Definite,
        };
        assert_eq!(
            evidence.validate(),
            Err(EvidenceValidationError::EmptyRuleId)
        );

        evidence.rule_id = "rule.1".to_string();
        evidence.rule_version = 0;
        assert_eq!(
            evidence.validate(),
            Err(EvidenceValidationError::ZeroRuleVersion)
        );

        evidence.rule_version = 1;
        evidence.owning_tool = "   ".to_string();
        assert_eq!(
            evidence.validate(),
            Err(EvidenceValidationError::EmptyOwningTool)
        );

        evidence.owning_tool = "Tool".to_string();
        evidence.matched_reason = "".to_string();
        assert_eq!(
            evidence.validate(),
            Err(EvidenceValidationError::EmptyMatchedReason)
        );
    }
}
